#ifndef TEXT_H
#define TEXT_H

#define DEFAULT_TEXT_PT 72
#define MAX_TEXT 1000

/* Please keep these on separate lines */
extern char path_bold_bitstreamVeraSans[];
extern char path_bold_bitstreamVeraSansMono[];
extern char path_bold_freeSans[];

extern char path_italic_crillee[];

extern char path_regular_freeSans[];
/* End font paths */

extern GLuint text[]; /* Store space for text textures only! Generated by SDL_ttf */

GLint text_getHeight(const char text[], TTF_Font *font, GLuint ptsize);
GLint text_getWidth(const char text[], TTF_Font *font, GLuint ptsize);

GLint text_load(const char input[], TTF_Font *font, SDL_Color color, GLuint index);

#endif
