#ifndef TEXT_H
#define TEXT_H

#define DEFAULT_TEXT_PT 72
#define MAX_TEXT 1000

typedef char font_p;
typedef GLuint text_i;

/* Please keep these on separate lines */
extern font_p path_bold_bitstreamVeraSans[];
extern font_p path_bold_bitstreamVeraSansMono[];
extern font_p path_bold_freeSans[];

extern font_p path_italic_crillee[];

extern font_p path_regular_freeSans[];
/* End font paths */

extern GLuint text[]; /* Store space for text textures only! Generated by SDL_ttf */

GLfloat text_scaleWidth(const char text[], TTF_Font *font, GLfloat textureHeight);
GLvoid text_position(GLfloat vertexX[], GLfloat vertexY[], GLfloat vertexZ[]);
GLint text_getHeight(const char text[], TTF_Font *font);
GLint text_getWidth(const char text[], TTF_Font *font);
GLint text_load(const char input[], TTF_Font *font, SDL_Color color, GLuint index);

#endif
