#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

#include <GL/gl.h>
#include <GL/glext.h>
#include <GL/glu.h>
#include <GL/glut.h>

#include <SDL/SDL.h>
#include <SDL/SDL_image.h>
#include <SDL/SDL_ttf.h>

#define MAX_IMAGES 20
#define MAX_TEXT 50

/* Variables */
typedef struct {
  bool mainMenu;
  bool multiPlayer;
  bool online;
  bool options;
  bool instruments;
  bool songs;
  bool difficulty;
  bool game;
} tCurrentScreen;

extern tCurrentScreen currentScreen;
extern GLuint nPlayers;
extern GLuint texture[]; /* Storage space for textures; this is the maximum at any given time */
extern GLuint text[]; /* Store space for text textures only! Generated by SDL_ttf */

/* General functions only */
GLvoid quitGame(GLint retnCode);

/* Other screens */
GLvoid screenDemo();
